services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/tuum"
    depends_on:
      - db
      - rabbit
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=tuum"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
